const yaml = require('js-yaml');

class JfrogYml{

  constructor(results){
    this.yml = {
      resources : [],
      pipelines : [],
    };

    this.setResources(results);
    this.setPipelines(results);
  }

  setResources(results){
    const self = this;
    results.filter(result=>result.type=="resource").map(resourceResult=>{
      self.yml.resources.push(resourceResult.data);
    });
  }

  setPipelines(results){
    const self = this;
    
    results.filter(result=>result.type=="pipeline").forEach(pipelineResult=>{  
      const pipelineName = pipelineResult.data.name;
      const pipeline = {
        name: pipelineName,
        configuration: pipelineResult.data.configuration,
        steps : []
      }

      // Add all steps to pipeline
      results.filter(result=>result.type=="step" && result.pipeline==pipelineName).forEach(stepResult=>{
        pipeline.steps.push(stepResult.data);
      })

      self.yml.pipelines.push(pipeline);
    });
  }

  toString(){
    const ymlObj = JSON.parse(JSON.stringify(this.yml));
    const yamlString = 
    `# This is an autogenerated JFrog yml
# By Kaholo :)
#
${yaml.safeDump(ymlObj,{indent: 2})}
`;
    return yamlString;
  }
}

module.exports = JfrogYml;